name: 'Docker Image Transfer'
description: 'Pulls a Docker image from a registry and pushes it to another.'
author: 'alex289'
branding:
  icon: 'box'
  color: 'purple'

inputs:
  source:
    description: 'Source Docker image repository (e.g.: docker.io/user/source-repo:tag)'
    required: true
  destination:
    description: 'Destination Docker image repository (e.g.: docker.io/user/source-repo:tag)'
    required: true
  destination_registry:
    description: 'Destination Docker repository name (e.g.: docker.io/user/)'
    required: true
  source_registry_username:
    description: 'Username for the source registry'
    required: false
  destination_registry_username:
    description: 'Username for the destination registry'
    required: false
  source_registry_password:
    description: 'Password for the source registry'
    required: false
  destination_registry_password:
    description: 'Password for the destination registry'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SOURCE: ${{ inputs.source }}
    DESTINATION: ${{ inputs.destination }}
    DESTINATION_REGISTRY: ${{ inputs.destination_registry }}
    SOURCE_REGISTRY_USERNAME: ${{ inputs.source_registry_username }}
    DESTINATION_REGISTRY_USERNAME: ${{ inputs.destination_registry_username }}
    SOURCE_REGISTRY_PASSWORD: ${{ inputs.source_registry_password }}
    DESTINATION_REGISTRY_PASSWORD: ${{ inputs.destination_registry_password }}
